[package]
name = "rust_raytracing"
version = "0.1.0"
authors = ["FiloSanza <filippo.sanzani2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rand = "0.7.3"