[package]
name = "rust-raytracingv2"
version = "0.1.0"
authors = ["filippo.sanzani <filippo.sanzani2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
image = "0.23.4"
num = "0.2.1"